### ISSUE TITLE
Parameter expansion in environment variables

### ISSUE THREAD

**Issue by jloewe** [xxh/xxh-shell-zsh#14]
**Is your feature request related to a problem? Please describe.**
When passing environment variables to a remote host, they are interpreted as strings and no parameter expansion is done.

```yaml
hosts:
  "":
    +e:
        - STARSHIP_CONFIG="${XDG_CONFIG_HOME}/starship.toml"
```

*Current behaviour:*
```sh
remote ~> echo $STARSHIP_CONFIG
${XDG_CONFIG_HOME}/starship.toml
```

*My expectation:*
```sh
remote ~> echo $STARSHIP_CONFIG
/home/user/.config/starship.toml
```

**Describe the solution you'd like**

A simple solution could be to explicitly run the expansion after base64 decoding the environment variables.

https://github.com/xxh/xxh-shell-zsh/blob/c262881dd389abe2b3b15ca672c51b16d23028de/entrypoint.sh#L59
```sh
# after the line above run the parameter expansion explicitly
val=$(eval "echo \"$val\"")
```

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Hey! PR is welcome!
