### ISSUE TITLE
Terminfo not loaded properly for zsh-bin 4.0.1

### ISSUE THREAD

**Issue by w1kl4s** [xxh/xxh-shell-zsh#7]
**Local OS (where xxh is installed): Void Linux
**Destination host OS: Debian
**xxh version: xxh/0.8.7
**xxh-plugins installed: xxh-plugin-prerun-core, xxh-plugin-zsh-ohmyzsh

when zsh shell is used, terminfo is not properly loaded which basically makes terminal unusable. Running export for expected terminfo yields a surprising result:
```
export TERM=xterm-256color                                                                                  
zsh: can't find terminal definition for xterm-256color
```

despite terminfo being present in xxh shell dir:
```
➜  ~ find .xxh/ -iname '*xterm-256color*'                                                                        
.xxh/.xxh/shells/xxh-shell-zsh/build/zsh-bin/share/terminfo/78.zsh-bin/xterm-256color
.xxh/.xxh/shells/xxh-shell-zsh/build/zsh-bin/share/terminfo/73.zsh-bin/screen.xterm-256color
```

Nothing related in +v found.
**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Hi @w1kl4s! I can repeat this :(

Yeah, this looks like the behavior around terminfo was changed in the latest versions of zsh-bin. Thank you for reporting! 

As a workaround: *UPD: the workaround is not needed now, see the next messages in the thread.*

<details>

I suggest you to try xxh-shell-zsh 7fd010b or lower i.e.
```python
cd ~/.xxh/.xxh/shells/
rm -rf xxh-shell-zsh
git clone https://github.com/xxh/xxh-shell-zsh
cd xxh-shell-zsh && git checkout 7fd010b
xxh host +s zsh +if
```

</details>

**Comment by anki-code** [comment]
I've reverted the zsh-bin version from 4.0.1 to 3.0.1 and terminfo works as expected as well as zsh and OhMyZsh. 

Hi @chitoku-k! If you have time please deep dive into zsh-bin v4 and v5 to resolve terminfo issues in the higher versions. Thanks!

Hi @w1kl4s! Now you can use the common use case:

```python
xxh +RI xxh-shell-zsh     # reinstall the local xxh-shell
xxh yourhost +s zsh +if   # connect to your host with updating the xxh-shell
```

Thanks for reporting!

**Comment by chitoku-k** [comment]
@anki-code OK, I will try to dig into it in my spare time!
